# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.9.0

# Install the codecov pip dependency
install:
  - pip install coverage
  - pip install pytest
  - pip install codecov
  - pip install pytest-cov
  

# Run the unit test
script:
  - pytest --cov-report term --cov=investpy tests/


after_success:
  - bash <(curl -s https://codecov.io/bash)